CREATE TABLE IF NOT EXISTS users (
	ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
	FIRSTNAME VARCHAR(255),
	SURNAME VARCHAR(255),
	PATRONYMIC VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    PHONE_NUMBER VARCHAR(15),
    BIRTH_DATE DATE,
    PHOTO VARCHAR(255),

    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) DEFAULT 'ROLE_USER'
    CHECK (ROLE IN ('ROLE_ADMIN','ROLE_USER','ROLE_MODERATOR')),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    VERSION BIGINT DEFAULT 1,
    PRIMARY KEY (ID),
    CONSTRAINT PHONE_NUMBER_FORMAT CHECK (PHONE_NUMBER ~ '^\+\d{1,14}$')
);

INSERT INTO users (firstname, surname, patronymic,
email, username, phone_number, birth_date, password)
VALUES
('Andrey', 'Vorobyev', 'Andreevich', 'andrey.vorobyev@example.com', 'vorobyev_aa', '+79991234567', '1993-06-25', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Ivan', 'Ivanov', 'Sergeevich', 'ivan.ivanov@example.com', 'ivanov_is', '+79101234567', '1985-02-14', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Petr', 'Petrov', 'Petrovich', 'petr.petrov@example.com', 'petrov_pp', '+79261234567', '1990-05-21', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Sergey', 'Sergeev', 'Ivanovich', 'sergey.sergeev@example.com', 'sergeev_si', '+79371234567', '1988-08-10', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Olga', 'Sidorova', 'Petrovna', 'olga.sidorova@example.com', 'sidorova_op', '+79451234567', '1995-12-30', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Maria', 'Ivanova', 'Sergeevna', 'maria.ivanova@example.com', 'ivanova_ms', '+79551234567', '1992-07-16', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Nikolay', 'Fedorov', 'Nikolaevich', 'nikolay.fedorov@example.com', 'fedorov_nn', '+79601234567', '1987-03-04', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Elena', 'Kuznetsova', 'Alekseevna', 'elena.kuznetsova@example.com', 'kuznetsova_ea', '+79671234567', '1994-09-12', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Dmitry', 'Zaitsev', 'Igorevich', 'dmitry.zaitsev@example.com', 'zaitsev_di', '+79871234567', '1991-04-22', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Ekaterina', 'Smirnova', 'Vladimirovna', 'ekaterina.smirnova@example.com', 'smirnova_ev', '+79751234567', '1989-11-17', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK');

INSERT INTO users (email, username, role, password)
VALUES
('admin', 'admin', 'ROLE_ADMIN', '$2a$12$UOLfDL9DUHZU3TFYcAc9NONr.IGtQkm3fJXI3N/xWlvrGJQND2uju');

