CREATE TABLE IF NOT EXISTS users (
	ID BIGINT GENERATED BY DEFAULT AS IDENTITY,
	FIRSTNAME VARCHAR(100) NOT NULL,
	SURNAME VARCHAR(100) NOT NULL,
	PATRONYMIC VARCHAR(255),
    EMAIL VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(15),
    BIRTH_DATE DATE,
    PHOTO  VARCHAR(255),
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) DEFAULT 'USER' CHECK (ROLE IN ('ADMIN','USER')),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    VERSION BIGINT DEFAULT 1,
    PRIMARY KEY (ID),
    CONSTRAINT PHONE_NUMBER_FORMAT CHECK (PHONE_NUMBER ~ '^\+\d{1,14}$')
);

INSERT INTO users (firstname, surname, patronymic,
email, username, phone_number, birth_date, password)
VALUES
('Ivan', 'Ivanov', 'Sergeevich', 'ivan.ivanov@example.com', 'Ivanov_IS', '+79101234567', '1985-02-14', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Petr', 'Petrov', 'Petrovich', 'petr.petrov@example.com', 'Petrov_PP', '+79261234567', '1990-05-21', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Sergey', 'Sergeev', 'Ivanovich', 'sergey.sergeev@example.com', 'Sergeev_SI', '+79371234567', '1988-08-10', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Olga', 'Sidorova', 'Petrovna', 'olga.sidorova@example.com', 'Sidorova_OP', '+79451234567', '1995-12-30', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Maria', 'Ivanova', 'Sergeevna', 'maria.ivanova@example.com', 'Ivanova_MS', '+79551234567', '1992-07-16', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Nikolay', 'Fedorov', 'Nikolaevich', 'nikolay.fedorov@example.com', 'Fedorov_NN', '+79601234567', '1987-03-04', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Elena', 'Kuznetsova', 'Alekseevna', 'elena.kuznetsova@example.com', 'Kuznetsova_EA', '+79671234567', '1994-09-12', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Dmitry', 'Zaitsev', 'Igorevich', 'dmitry.zaitsev@example.com', 'Zaitsev_DI', '+79871234567', '1991-04-22', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Ekaterina', 'Smirnova', 'Vladimirovna', 'ekaterina.smirnova@example.com', 'Smirnova_EV', '+79751234567', '1989-11-17', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK'),
('Andrey', 'Vorobyev', 'Andreevich', 'andrey.vorobyev@example.com', 'Vorobyev_AA', '+79991234567', '1993-06-25', '$2a$12$SQ./CdZ8r.pV3WmPSjv3x.44//hq5/RM9eRxbULA4daANkit0jOrK');